### ISSUE TITLE
could not find function "rulemodelAccuracy"

### ISSUE THREAD

**Issue by william-vw** [kliegr/arc#4]
Hi all,

When running the code sample from the GitHub home page I'm getting the following error:
```
Error in rulemodelAccuracy(prediction, test[[classatt]]) : 
  could not find function "rulemodelAccuracy"
```

All prior steps are being properly executed. Any ideas?

Thanks,

William

**Comment by kliegr** [comment]
Thanks for spotting this.
This step should read:

      acc <- CBARuleModelAccuracy(prediction, test[[classatt]])

Corrected
